#!/bin/bash

xrandrOut=$(xrandr)

hdmiName=$(echo "${xrandrOut}" | grep -i 'HDMI' | awk '{print $1}')
dpName=$(echo "${xrandrOut}" | grep -i '^DP1-2' | awk '{print $1}')
edpName=$(echo "${xrandrOut}" | grep -i 'EDP' | awk '{print $1}')

allDisplays=$(echo "${xrandrOut}" | sed -n "s/^\(.*\) \w*connected$/\1/p")
connectedDisplays=$(echo "${xrandrOut}" | grep " connected" | sed -e "s/\([A-Z0-9]\+\) connected.*/\1/")
activeDisplays=$(comm <(echo $displays) <(echo $connectedDisplays) --nocheck-order -1)
displayFile='/tmp/.allDisplays'

if [[ -f "${displayFile}" ]]; then
    oldDisplays=$(cat "${displayFile}")
else
    oldDisplays=""
fi

if [[ "${oldDisplays}" != "${connectedDisplays}" ]]; then
    change="yes"
else
    change="no"
fi

label=$(echo $activeDisplays | tr -s '\n' ' ')

echo $label
echo $label
echo ""

if [[ "${change}" = "yes" ]]; then
  xrandr --auto
  autorandr --change
  echo "${connectedDisplays}" > "${displayFile}"
fi
