#!/bin/bash
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

INTERFACE="wlp2s0"

SOFT_BLOCKED=$(rfkill list 1 | grep "Soft blocked: yes")

# If the interface is softblocked
if [[ $SOFT_BLOCKED != "" ]]; then
  echo "WiFi softblock"
  exit
fi

# If the interface is down
if [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]]; then
  echo "WiFi down"
  exit
fi

QUALITY=$(iwlist $INTERFACE scan | awk '/Quality/ {split($1,a,"="); split(a[2],b,"/"); print int(b[1] * 100 / 70)}' | tail -n1)
SSID=$(iwlist $INTERFACE scan | awk '/ESSID/ {split($1,a,"\""); print a[2]}')
SOFT_BLOCKED=$(rfkill list 1 | grep "Soft blocked: yes")

# If the length is too long
if [ "${#SSID}" -gt "32" ]; then
  echo "Scanning..."
  echo "Scanning..."
  echo \#FFF600
fi

#------------------------------------------------------------------------

echo $QUALITY% at $SSID # full text
echo $QUALITY% # short text

# color
if [[ $QUALITY -ge 80 ]]; then
  echo "#00FF00"
elif [[ $QUALITY -lt 80 ]]; then
  echo "#FFF600"
elif [[ $QUALITY -lt 60 ]]; then
  echo "#FFAE00"
elif [[ $QUALITY -lt 40 ]]; then
  echo "#FF0000"
fi
